language: c

sudo: true

matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
    compiler: gcc
  - os: linux
    sudo: required
    dist: trusty
    compiler: clang
  - os: linux
    sudo: required
    dist: xenial
    compiler: gcc
  - os: linux
    sudo: required
    dist: xenial
    compiler: clang
  - os: osx
    sudo: required
    compiler: gcc
  - os: osx
    sudo: required
    compiler: clang

install:
  - curl https://corto.io/ci-dev | sh

script:
  - corto test
